### ISSUE TITLE
(Some) Windows versions require GID 1 to be blank for COLRv0 fonts

### ISSUE THREAD

**Issue by khaledhosny** [djrrb/Bungee#86] opened 2022-12-10 13:27 UTC
See https://github.com/googlefonts/gftools/issues/609

I hit the same issue testing Bungee on LibreOffice for Windows, you get:
![Bungee](https://user-images.githubusercontent.com/93914/206857521-2e4bd9a7-e8c2-4731-be69-dede19710159.png)

(the glyph in the background is GID 1 which happens to be `Eth` in Bungee).

**Comment by justvanrossum** [comment] 2022-12-10 13:32
We should probably fix this by having the first 4 gids conform to the recommendations.

**Comment by justvanrossum** [comment] 2024-06-29 13:31
In the current release (2.000) gid 1 is "space" and is blank in all fonts. So while it isn't `/.null` as per recommendation, the problem as reported should be resolved.

**Comment by justvanrossum** [comment] 2024-06-29 13:43
Ah, this is a duplicate of #53. Since the symptoms mentioned here should be resoved, I will close this issue.

**Closed by justvanrossum** 2024-06-29 13:43 UTC
Labels: bug
